data_sets:
    - name: HG000096
      path: FASTQ/RNAseq/HG000096
      paired: True
      readsfile1: HG000096_1.fastq
      readsfile2: HG000096_2.fastq
      sex: M
      population: ---
      superpop: ---
      SRA: a


reference_genomes:
    - name: hg38
      species: homo sapiens
#      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dmel-all-chromosome-r6.13.fasta
#      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dmel-all-chromosome-r6.13.fasta.fai
#      bowtie: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dmel-all-chromosome-r6.13_bowtie/dmel-r6.13
#      split: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dmel-all-chromosome-r6.13_split/
#      source: Flybase




annotations:
    - name: hg38_
      bed_path: /proj/cdjones_lab/Genomics_Data_Commons/annotations/drosophila_melanogaster/dmel-all-r6.13.bed
      gtf_path: /proj/cdjones_lab/Genomics_Data_Commons/annotations/drosophila_melanogaster/dmel-all-r6.13.gtf
      derived: False
